# Generated by Django 3.2.13 on 2022-10-01 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blockchain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('hash', models.CharField(max_length=200)),
                ('timestamp', models.CharField(max_length=200)),
                ('nonce', models.CharField(max_length=10)),
                ('transactions', models.TextField()),
                ('owner', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='plots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_public_key', models.CharField(max_length=1000)),
                ('hash', models.CharField(max_length=200)),
                ('coords', models.CharField(max_length=10)),
                ('landscape', models.TextField()),
                ('owner', models.CharField(max_length=100)),
            ],
        ),
    ]
